services:
  mysql:
    image: mysql:8.4
    container_name: healthsense-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthsense
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: healthsense-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: