package fit.iuh.se.hsoperations.entity.enums;

public enum NeedsActionType {
    PAYMENT_REQUIRES_REVIEW,
    PROVIDER_CANCELLATION_RECONCILIATION,
    REFUND_REVIEW_REQUIRED,
    REFUND_PROVIDER_FAILURE,
    DOCTOR_ACTIVE_CARE_INTERRUPTION,
    MEMBER_ACTIVE_CARE_INTERRUPTION,
    TERMINATION_REVIEW,
    SUMMARY_PENDING,
    SUMMARY_OVERDUE,
    SUMMARY_ESCALATED
}
