package fit.iuh.se.hschat.entity.enums;

public enum CareServiceCode {
    REMOTE_ONE_ON_ONE_CARE,
    SECURE_MESSAGING,
    HEALTH_RECORD_REVIEW,
    AI_SCREENING_REVIEW,
    CARE_MONITORING,
    FINAL_CARE_SUMMARY,
    EMERGENCY_CARE,
    TWENTY_FOUR_SEVEN_SUPPORT,
    FORMAL_DIAGNOSIS,
    PRESCRIPTION,
    VIDEO_CONSULTATION
}
