-- =====================================================================
-- V22: Danh muc dinh duong co khuyen nghi lam sang
-- Additive: chi tao bang moi. Gia tri dinh duong KHONG luu o day ma doc tu
-- nutrition_foods (V21) qua nutrition_food_id, nen khong bi lech so lieu.
-- =====================================================================

CREATE TABLE nutrition_food_groups (
    id VARCHAR(40) PRIMARY KEY,
    slug VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    dietary_pattern VARCHAR(20) NOT NULL
        CHECK (dietary_pattern IN ('PRIORITIZE', 'LIMIT', 'CAUTION', 'BALANCED')),
    icon VARCHAR(40),
    image_url VARCHAR(500),
    display_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ,
    created_by VARCHAR(255), updated_by VARCHAR(255)
);

CREATE TABLE nutrition_evidence_sources (
    id VARCHAR(60) PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source_type VARCHAR(30) NOT NULL
        CHECK (source_type IN ('GUIDELINE', 'SYSTEMATIC_REVIEW', 'META_ANALYSIS', 'RCT', 'OTHER')),
    authors VARCHAR(300),
    journal VARCHAR(200),
    publication_year INTEGER,
    url VARCHAR(500),
    summary VARCHAR(1000),
    created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ,
    created_by VARCHAR(255), updated_by VARCHAR(255)
);

CREATE TABLE nutrition_guidance_foods (
    id VARCHAR(60) PRIMARY KEY,
    group_id VARCHAR(40) NOT NULL REFERENCES nutrition_food_groups(id),
    nutrition_food_id BIGINT NOT NULL REFERENCES nutrition_foods(id),
    food_name VARCHAR(120) NOT NULL,
    food_name_specific VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    guidance VARCHAR(20) NOT NULL CHECK (guidance IN ('PRIORITIZE', 'LIMIT', 'CAUTION')),
    guidance_title VARCHAR(200) NOT NULL,
    guidance_reason VARCHAR(1000) NOT NULL,
    cardiovascular_context VARCHAR(1000),
    af_context VARCHAR(1000),
    medication_context VARCHAR(1000),
    highlight_nutrient_codes VARCHAR(200) NOT NULL,
    image_url VARCHAR(500),
    search_text VARCHAR(2000) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ,
    created_by VARCHAR(255), updated_by VARCHAR(255)
);

COMMENT ON COLUMN nutrition_guidance_foods.highlight_nutrient_codes IS 'Ma chat dinh duong noi bat, cach nhau bang dau phay, dung thu tu hien thi';
COMMENT ON COLUMN nutrition_guidance_foods.search_text IS 'Chu thuong, bo dau tieng Viet: ten mon + ten cu the + ten nguon + mo ta';

CREATE INDEX idx_nutrition_guidance_food_group ON nutrition_guidance_foods (group_id, display_order);
CREATE INDEX idx_nutrition_guidance_food_name ON nutrition_guidance_foods (food_name);
CREATE INDEX idx_nutrition_guidance_food_source ON nutrition_guidance_foods (nutrition_food_id);

CREATE TABLE nutrition_guidance_food_evidence (
    guidance_food_id VARCHAR(60) NOT NULL REFERENCES nutrition_guidance_foods(id) ON DELETE CASCADE,
    evidence_source_id VARCHAR(60) NOT NULL REFERENCES nutrition_evidence_sources(id),
    display_order INTEGER NOT NULL,
    PRIMARY KEY (guidance_food_id, evidence_source_id)
);

CREATE INDEX idx_nutrition_guidance_evidence_source ON nutrition_guidance_food_evidence (evidence_source_id);

-- ---------------------------------------------------------------------
-- Du lieu ban dau: chuyen tu du lieu mau cua Frontend (29 mon, 8 nhom, 6 nguon).
-- ---------------------------------------------------------------------

INSERT INTO nutrition_food_groups (id, slug, name, description, dietary_pattern, icon, image_url, display_order, created_at, updated_at, created_by, updated_by) VALUES
('FISH', 'fish-seafood', 'Cá & Hải sản', 'Nhóm thường được khuyến khích trong chế độ ăn tốt cho tim mạch nhờ giàu axit béo Omega-3.', 'PRIORITIZE', 'Fish', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('DAIRY', 'dairy', 'Sữa & Chế phẩm từ sữa', 'Nguồn cung cấp canxi và protein dồi dào. Lựa chọn dạng ít béo giúp kiểm soát chất béo bão hòa.', 'BALANCED', 'Milk', NULL, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('VEGETABLE', 'vegetables', 'Rau củ', 'Giàu chất xơ, kali và các chất chống oxy hóa tự nhiên hỗ trợ duy trì huyết áp và tim mạch.', 'PRIORITIZE', 'Carrot', NULL, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('FRUIT', 'fruits', 'Trái cây', 'Cung cấp vitamin, khoáng chất điện giải tự nhiên và chất xơ hòa tan.', 'PRIORITIZE', 'Apple', NULL, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('LEGUMES_NUTS', 'legumes-nuts', 'Đậu & Hạt dinh dưỡng', 'Nguồn chất béo chưa bão hòa, đạm thực vật và magie dồi dào có lợi cho tim.', 'PRIORITIZE', 'Nut', NULL, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('BEVERAGES_CAUTION', 'beverages-caution', 'Đồ uống cần theo dõi', 'Các loại đồ uống chứa caffeine cần lưu ý ngưỡng tiêu thụ cá nhân và phản xạ nhịp tim.', 'CAUTION', 'Coffee', NULL, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('BEVERAGES_ALCOHOL', 'beverages-alcohol', 'Đồ uống có cồn', 'Nhóm nên hạn chế tối đa vì liên quan đến nguy cơ kích phát hoặc tái phát rung nhĩ.', 'LIMIT', 'Wine', NULL, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('PROCESSED_FOODS', 'processed-foods', 'Thực phẩm chế biến sẵn & Nhiều muối', 'Thường có lượng natri và chất béo bão hòa cao, dễ làm tăng gánh nặng lên huyết áp.', 'LIMIT', 'Beef', NULL, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22');

INSERT INTO nutrition_evidence_sources (id, title, source_type, authors, journal, publication_year, url, summary, created_at, updated_at, created_by, updated_by) VALUES
('acc-aha-2023', '2023 ACC/AHA/ACCP/HRS Guideline for the Diagnosis and Management of Atrial Fibrillation', 'GUIDELINE', 'Joglar JA, Chung MK, Armbruster AL, et al.', 'Circulation / JACC', 2023, 'https://www.ahajournals.org/doi/10.1161/CIR.0000000000001193', 'Khuyến cáo quản lý toàn diện yếu tố lối sống, hạn chế rượu bia và duy trì dinh dưỡng lành mạnh cho tim mạch ở bệnh nhân rung nhĩ.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('aha-lifestyle-2020', 'Lifestyle and Risk Factor Modification for Reduction of Atrial Fibrillation: A Scientific Statement From the American Heart Association', 'GUIDELINE', 'Chung MK, Eckhardt LL, Chen LY, et al.', 'Circulation', 2020, 'https://www.ahajournals.org/doi/10.1161/CIR.0000000000000748', 'Tổng hợp bằng chứng về giảm cân, kiểm soát huyết áp, chế độ ăn Địa Trung Hải và các yếu tố kích hoạt kịch phát AF.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('predimed-trial', 'Extravirgin olive oil consumption reduces risk of atrial fibrillation: the PREDIMED trial', 'RCT', 'Martínez-González MÁ, Toledo E, Arós F, et al.', 'Circulation', 2014, 'https://pubmed.ncbi.nlm.nih.gov/24787471/', 'Thử nghiệm ngẫu nhiên có đối chứng cho thấy chế độ ăn Địa Trung Hải giàu chất béo chưa bão hòa có liên quan đến việc giảm nguy cơ AF.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('coffee-af-meta-2021', 'Coffee and Caffeine Consumption and Risk of Atrial Fibrillation: A Systematic Review and Meta-Analysis', 'META_ANALYSIS', 'Grobbee DE, et al.', 'European Journal of Preventive Cardiology', 2021, 'https://pubmed.ncbi.nlm.nih.gov/39149585/', 'Tiêu thụ caffeine ở mức độ vừa phải (1-3 tách cà phê mỗi ngày) không liên quan đến tăng nguy cơ rung nhĩ trong dân số chung.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('alcohol-af-review', 'Alcohol Consumption and Risk of Atrial Fibrillation: A Dose-Response Meta-Analysis', 'SYSTEMATIC_REVIEW', 'Larsson SC, Drca N, Wolk A.', 'Journal of the American College of Cardiology', 2014, 'https://health.clevelandclinic.org/managing-your-atrial-fibrillation-what-to-eat-and-avoid', 'Nguy cơ xuất hiện hoặc tái phát AF tăng theo liều lượng cồn tiêu thụ, ngay cả ở mức độ uống vừa phải đến nhiều.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('cleveland-dietary-af', 'Managing Your Atrial Fibrillation: What to Eat and Avoid', 'OTHER', 'Cleveland Clinic Heart, Vascular & Thoracic Institute', 'Cleveland Clinic Health Essentials', 2023, 'https://health.clevelandclinic.org/managing-your-atrial-fibrillation-what-to-eat-and-avoid', 'Hướng dẫn thực hành lâm sàng cho bệnh nhân rung nhĩ về natri, kali, magie, caffeine và tương tác thuốc kháng đông.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22');

-- nutrition_food_id tra theo ma FNDDS; ma khong ton tai se lam migration dung lai (NOT NULL).
INSERT INTO nutrition_guidance_foods (id, group_id, nutrition_food_id, food_name, food_name_specific, description, guidance, guidance_title, guidance_reason, cardiovascular_context, af_context, medication_context, highlight_nutrient_codes, image_url, search_text, display_order, created_at, updated_at, created_by, updated_by) VALUES
('milk-low-fat-1', 'DAIRY', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '11112210'), 'Sữa', 'Sữa ít béo 1%', 'Sữa bò có hàm lượng chất béo khoảng 1%, ít chất béo bão hòa hơn sữa nguyên kem trong khi vẫn giàu canxi và kali.', 'PRIORITIZE', 'Phù hợp trong chế độ ăn tốt cho tim mạch', 'Lượng chất béo bão hòa thấp (0.6g/100g), giúp hạn chế cholesterol xấu LDL mà vẫn duy trì đủ đạm và khoáng chất.', 'Ưu tiên các nguồn sữa ít béo hoặc tách béo giúp hạn chế lượng chất béo bão hòa nạp vào, hỗ trợ duy trì mức lipid máu ổn định.', 'Chứa kali và magie — các chất điện giải có vai trò trong hoạt động điện bình thường của tim.', NULL, 'protein,fat_saturated,sodium,potassium', NULL, 'sua sua it beo 1% milk, low fat (1%) sua bo co ham luong chat beo khoang 1%, it chat beo bao hoa hon sua nguyen kem trong khi van giau canxi va kali.', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('milk-skim', 'DAIRY', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '11113000'), 'Sữa', 'Sữa tách béo (Skim milk)', 'Sữa bò đã được tách béo hoàn toàn (fat-free), hàm lượng calo và chất béo bão hòa thấp nhất.', 'PRIORITIZE', 'Lựa chọn nạc tối ưu cho người kiểm soát mỡ máu & cân nặng', 'Lượng chất béo bão hòa gần như bằng 0 (dưới 0.1g/100g), phù hợp với người cần kiểm soát chặt chẽ lipid máu.', 'Giúp đáp ứng nhu cầu vi chất canxi và kali mà không làm tăng lượng chất béo bão hòa trong ngày.', 'Cung cấp khoáng chất điện giải hỗ trợ dẫn truyền thần kinh cơ tim.', NULL, 'protein,fat_saturated,sodium,potassium', NULL, 'sua sua tach beo (skim milk) milk, fat free (skim) sua bo da duoc tach beo hoan toan (fat-free), ham luong calo va chat beo bao hoa thap nhat.', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('milk-reduced-fat-2', 'DAIRY', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '11112110'), 'Sữa', 'Sữa giảm béo 2%', 'Sữa giảm béo vừa phải, giữ độ thơm béo tự nhiên nhẹ với lượng chất béo bão hòa trung bình.', 'PRIORITIZE', 'Lựa chọn chuyển tiếp hợp lý', 'Chất béo bão hòa thấp hơn sữa nguyên kem (khoảng 1.1g/100g), có thể dùng xen kẽ trước khi chuyển sang loại 1% hoặc tách béo.', 'Cân nhắc tổng lượng chất béo bão hòa từ các bữa ăn khác trong ngày để giữ ở mức khuyến nghị dưới 10% tổng năng lượng.', NULL, NULL, 'protein,fat_saturated,sodium,potassium', NULL, 'sua sua giam beo 2% milk, reduced fat (2%) sua giam beo vua phai, giu do thom beo tu nhien nhe voi luong chat beo bao hoa trung binh.', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('milk-whole', 'DAIRY', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '11111000'), 'Sữa', 'Sữa nguyên kem', 'Sữa bò nguyên chất giữ nguyên độ béo tự nhiên (khoảng 3.2g chất béo/100g).', 'CAUTION', 'Cân nhắc lượng dùng nếu cần kiểm soát mỡ máu', 'Chứa lượng chất béo bão hòa cao hơn sữa ít béo hoặc tách béo (khoảng 1.9g/100g). Người có rối loạn lipid máu nên cân đối lượng nạp.', 'Hiệp hội Tim mạch Hoa Kỳ (AHA) khuyến nghị người trưởng thành nên ưu tiên sản phẩm từ sữa ít béo hoặc không béo để kiểm soát cholesterol LDL.', NULL, NULL, 'protein,fat_saturated,sodium,potassium', NULL, 'sua sua nguyen kem milk, whole sua bo nguyen chat giu nguyen do beo tu nhien (khoang 3.2g chat beo/100g).', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('milk-lactose-free-low-fat', 'DAIRY', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '11114300'), 'Sữa', 'Sữa không lactose ít béo 1%', 'Sữa ít béo đã được phân giải đường lactose, thân thiện với hệ tiêu hóa nhạy cảm.', 'PRIORITIZE', 'Lựa chọn tốt cho người không dung nạp lactose', 'Vừa kiểm soát chất béo bão hòa thấp, vừa tránh đầy hơi khó tiêu mà không làm giảm lượng canxi và kali.', NULL, NULL, NULL, 'protein,fat_saturated,sodium,potassium', NULL, 'sua sua khong lactose it beo 1% milk, lactose free, low fat (1%) sua it beo da duoc phan giai duong lactose, than thien voi he tieu hoa nhay cam.', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('milk-lactose-free-skim', 'DAIRY', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '11114320'), 'Sữa', 'Sữa không lactose tách béo', 'Sữa tách béo hoàn toàn kết hợp công nghệ loại bỏ đường lactose.', 'PRIORITIZE', 'Ít béo, không lactose, giàu khoáng chất', 'Hàm lượng chất béo bão hòa gần như bằng 0, an toàn cho cả tim mạch lẫn tiêu hóa.', NULL, NULL, NULL, 'protein,fat_saturated,sodium,potassium', NULL, 'sua sua khong lactose tach beo milk, lactose free, fat free (skim) sua tach beo hoan toan ket hop cong nghe loai bo duong lactose.', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('milk-lactose-free-whole', 'DAIRY', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '11114350'), 'Sữa', 'Sữa không lactose nguyên kem', 'Sữa nguyên chất không lactose giữ trọn vẹn chất béo tự nhiên.', 'CAUTION', 'Hỗ trợ tiêu hóa, cân nhắc lượng chất béo', 'Phù hợp người dị ứng lactose, nhưng giữ lượng chất béo bão hòa tương đương sữa nguyên kem thông thường.', NULL, NULL, NULL, 'protein,fat_saturated,sodium,potassium', NULL, 'sua sua khong lactose nguyen kem milk, lactose free, whole sua nguyen chat khong lactose giu tron ven chat beo tu nhien.', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('salmon-baked', 'FISH', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '26137120'), 'Cá hồi', 'Cá hồi nướng', 'Cá hồi được nướng chín mộc hoặc áp chảo với ít dầu, giữ lại tối đa nguồn axit béo omega-3 quý giá.', 'PRIORITIZE', 'Rất khuyến khích cho sức khỏe tim mạch', 'Giàu axit béo omega-3 chuỗi dài (EPA và DHA) và protein chất lượng cao, đồng thời natri tự nhiên thấp.', 'Chế độ ăn giàu cá béo (2 bữa/tuần) được khuyến cáo bởi các hướng dẫn tim mạch lớn để giảm nguy cơ bệnh mạch vành và hỗ trợ điều hòa lipid máu.', 'Các nghiên cứu dịch tễ và thử nghiệm chế độ ăn Địa Trung Hải cho thấy dinh dưỡng giàu omega-3 tự nhiên hỗ trợ bảo vệ mô cơ tim và nội mạc mạch máu.', NULL, 'protein,epa,dha,sodium', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80', 'ca hoi ca hoi nuong fish, salmon, baked or broiled ca hoi duoc nuong chin moc hoac ap chao voi it dau, giu lai toi da nguon axit beo omega-3 quy gia.', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('salmon-fried', 'FISH', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '26137140'), 'Cá hồi', 'Cá hồi chiên ngập dầu', 'Cá hồi tẩm bột chiên ngập dầu làm tăng đáng kể tổng calo, chất béo chuyển hóa và natri.', 'LIMIT', 'Nên hạn chế cách chế biến chiên giòn', 'Quá trình chiên ngập dầu làm giảm giá trị của omega-3 và bổ sung lượng lớn chất béo xấu cùng natri từ lớp bột tẩm.', 'Thay vì chiên ngập dầu, các chuyên gia khuyến khích phương pháp áp chảo nhẹ, hấp hoặc nướng cùng gia vị thảo mộc tự nhiên.', NULL, NULL, 'fat_total,fat_saturated,sodium,energy', NULL, 'ca hoi ca hoi chien ngap dau fish, salmon, fried ca hoi tam bot chien ngap dau lam tang dang ke tong calo, chat beo chuyen hoa va natri.', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('mackerel-grilled', 'FISH', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '26121120'), 'Cá thu', 'Cá thu nướng', 'Cá thu biển nướng mộc, nguồn cung cấp khoáng chất và omega-3 nồng độ cao.', 'PRIORITIZE', 'Nguồn omega-3 biển sâu dồi dào', 'Chứa hàm lượng EPA và DHA rất cao, cùng với magie tự nhiên tốt cho cơ tim.', 'Thuộc nhóm cá béo lý tưởng trong mô hình ăn uống có lợi cho hệ tuần hoàn.', NULL, NULL, 'protein,epa,dha,magnesium', NULL, 'ca thu ca thu nuong fish, mackerel, baked or broiled ca thu bien nuong moc, nguon cung cap khoang chat va omega-3 nong do cao.', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('tuna-canned', 'FISH', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '26155110'), 'Cá ngừ', 'Cá ngừ đóng hộp (ngâm nước)', 'Cá ngừ ngâm nước cung cấp nguồn đạm nạc, ít chất béo, tiện lợi cho bữa ăn hàng ngày.', 'PRIORITIZE', 'Nguồn đạm nạc tiện dụng', 'Rất ít chất béo bão hòa, tuy nhiên cần lưu ý kiểm tra nhãn để tránh loại ngâm muối quá nhiều natri.', NULL, NULL, NULL, 'protein,sodium,energy,fat_total', NULL, 'ca ngu ca ngu dong hop (ngam nuoc) fish, tuna, canned ca ngu ngam nuoc cung cap nguon dam nac, it chat beo, tien loi cho bua an hang ngay.', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('spinach-cooked', 'VEGETABLE', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '72125211'), 'Rau chân vịt', 'Rau chân vịt luộc', 'Rau cải bó xôi nấu chín mộc không thêm dầu mỡ, giàu kali, magie và chất xơ.', 'PRIORITIZE', 'Thực phẩm vàng cho chế độ ăn tim mạch', 'Hàm lượng kali và magie tự nhiên cao, ít calo và giàu chất xơ.', 'Chế độ ăn giàu rau lá xanh đậm là trụ cột của chế độ ăn DASH và Địa Trung Hải giúp hỗ trợ kiểm soát huyết áp.', 'Kali và magie là các chất điện giải có vai trò trong hoạt động điện bình thường của tim.', 'Nếu bạn đang sử dụng warfarin, lượng vitamin K trong chế độ ăn nên được duy trì tương đối ổn định. Không cần tự ý loại bỏ hoàn toàn các thực phẩm giàu vitamin K, mà nên trao đổi với bác sĩ để điều chỉnh liều thuốc tương thích với thói quen ăn uống.', 'vitamin_k,potassium,magnesium,fiber', NULL, 'rau chan vit rau chan vit luoc spinach, fresh, cooked, no added fat rau cai bo xoi nau chin moc khong them dau mo, giau kali, magie va chat xo.', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('spinach-raw', 'VEGETABLE', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '72125100'), 'Rau chân vịt', 'Rau chân vịt tươi sống', 'Lá rau non tươi giòn, thích hợp dùng làm salad hoặc sinh tố xanh.', 'PRIORITIZE', 'Giàu vi chất tự nhiên chưa qua nhiệt', 'Bảo toàn tối đa vitamin C, folate và các chất chống oxy hóa tự nhiên.', NULL, NULL, 'Người dùng thuốc chống đông warfarin cần duy trì lượng ăn ổn định như với rau chân vịt nấu chín.', 'vitamin_k,potassium,magnesium,fiber', NULL, 'rau chan vit rau chan vit tuoi song spinach, raw la rau non tuoi gion, thich hop dung lam salad hoac sinh to xanh.', 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('broccoli-cooked', 'VEGETABLE', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '72201190'), 'Bông cải xanh', 'Bông cải xanh luộc', 'Súp lơ xanh luộc chín tới, giàu chất xơ, vitamin C, kali và sulforaphane.', 'PRIORITIZE', 'Nguồn chất xơ và vi chất tự nhiên dồi dào', 'Hàm lượng natri rất thấp, hỗ trợ sức khỏe thành mạch và tiêu hóa.', NULL, NULL, NULL, 'fiber,potassium,vitamin_k,energy', NULL, 'bong cai xanh bong cai xanh luoc broccoli, cooked, from restaurant sup lo xanh luoc chin toi, giau chat xo, vitamin c, kali va sulforaphane.', 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('tomato-raw', 'VEGETABLE', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '74101000'), 'Cà chua', 'Cà chua tươi', 'Cà chua chín mọng ăn sống hoặc nấu canh, giàu lycopene và kali.', 'PRIORITIZE', 'Giàu kali và chất chống oxy hóa tự nhiên', 'Rất ít năng lượng, không chất béo bão hòa, thích hợp dùng hàng ngày.', NULL, NULL, NULL, 'potassium,energy,fiber,sodium', NULL, 'ca chua ca chua tuoi tomatoes, raw ca chua chin mong an song hoac nau canh, giau lycopene va kali.', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('carrot-raw', 'VEGETABLE', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '73101010'), 'Cà rốt', 'Cà rốt tươi', 'Củ cà rốt giòn ngọt tự nhiên, giàu chất xơ và beta-carotene.', 'PRIORITIZE', 'Rau củ củ lành mạnh, vị ngọt thanh tự nhiên', 'Nguồn chất xơ tốt hỗ trợ điều hòa đường huyết và tiêu hóa.', NULL, NULL, NULL, 'fiber,potassium,energy,sugars', NULL, 'ca rot ca rot tuoi carrots, raw cu ca rot gion ngot tu nhien, giau chat xo va beta-carotene.', 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('banana-raw', 'FRUIT', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '63107010'), 'Chuối', 'Chuối chín tươi', 'Trái cây nhiệt đới ngọt dịu, nổi tiếng là nguồn bổ sung kali và magie tự nhiên dễ hấp thu.', 'PRIORITIZE', 'Nguồn khoáng chất điện giải tự nhiên', 'Cung cấp lượng kali và magie tự nhiên dồi dào, hỗ trợ cân bằng điện giải cho người ăn uống hàng ngày.', 'Chế độ ăn đủ kali từ rau củ quả hỗ trợ đào thải natri qua thận và duy trì mức huyết áp khỏe mạnh.', 'Kali và magie là các chất điện giải có vai trò trong hoạt động điện bình thường của tim.', NULL, 'potassium,magnesium,fiber,energy', NULL, 'chuoi chuoi chin tuoi banana, raw trai cay nhiet doi ngot diu, noi tieng la nguon bo sung kali va magie tu nhien de hap thu.', 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('apple-raw', 'FRUIT', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '63101000'), 'Táo', 'Táo tươi cả vỏ', 'Táo tươi giòn ngọt, giàu chất xơ hòa tan pectin và các hợp chất flavonoid.', 'PRIORITIZE', 'Giàu chất xơ hòa tan tốt cho mạch máu', 'Chất xơ pectin trong táo hỗ trợ giảm hấp thu cholesterol từ đường tiêu hóa.', NULL, NULL, NULL, 'fiber,energy,potassium,sugars', NULL, 'tao tao tuoi ca vo apple, raw tao tuoi gion ngot, giau chat xo hoa tan pectin va cac hop chat flavonoid.', 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('orange-raw', 'FRUIT', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '61119010'), 'Cam', 'Cam tươi', 'Cam tươi mọng nước, giàu vitamin C và chất chống oxy hóa tự nhiên.', 'PRIORITIZE', 'Bổ sung nước, vitamin và kali', 'Ưu tiên ăn nguyên múi cam thay vì chỉ uống nước ép để nhận được trọn vẹn chất xơ hòa tan.', NULL, NULL, NULL, 'potassium,fiber,energy,sugars', NULL, 'cam cam tuoi orange, raw cam tuoi mong nuoc, giau vitamin c va chat chong oxy hoa tu nhien.', 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('avocado-raw', 'FRUIT', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '63105010'), 'Quả bơ', 'Quả bơ tươi', 'Trái bơ giàu axit béo không bão hòa đơn (axit oleic) lành mạnh, giàu kali và magie.', 'PRIORITIZE', 'Chất béo lành mạnh thực vật', 'Chứa lượng chất béo chưa bão hòa đơn cao kết hợp lượng kali vượt trội so với hầu hết các loại trái cây.', 'Chất béo chưa bão hòa đơn có tác dụng hỗ trợ cải thiện chỉ số mỡ máu khi thay thế cho mỡ động vật giàu chất béo bão hòa.', NULL, NULL, 'fat_monounsaturated,potassium,fiber,magnesium', NULL, 'qua bo qua bo tuoi avocado, raw trai bo giau axit beo khong bao hoa don (axit oleic) lanh manh, giau kali va magie.', 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('almonds', 'LEGUMES_NUTS', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '42100100'), 'Hạt hạnh nhân', 'Hạt hạnh nhân sấy mộc', 'Hạnh nhân sấy mộc không muối đường, giàu magie, vitamin E và đạm thực vật.', 'PRIORITIZE', 'Món ăn nhẹ giàu magie và đạm thực vật', 'Hàm lượng magie tự nhiên cao (trên 250mg/100g) cùng chất xơ và chất béo lành mạnh.', NULL, 'Magie có vai trò hỗ trợ ổn định dẫn truyền thần kinh cơ và hoạt động điện bình thường của tim.', NULL, 'magnesium,protein,fiber,potassium', NULL, 'hat hanh nhan hat hanh nhan say moc almonds, nfs hanh nhan say moc khong muoi duong, giau magie, vitamin e va dam thuc vat.', 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('peanuts', 'LEGUMES_NUTS', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '42111000'), 'Đậu phộng', 'Đậu phộng rang mộc (không muối)', 'Đậu phộng rang không thêm muối, giàu protein thực vật và niacin.', 'PRIORITIZE', 'Nguồn đạm và khoáng chất thực vật tiết kiệm', 'Giàu protein thực vật và khoáng chất. Nên dùng loại rang không muối để tránh nạp thừa natri.', NULL, NULL, NULL, 'protein,magnesium,fiber,potassium', NULL, 'dau phong dau phong rang moc (khong muoi) peanuts, nfs dau phong rang khong them muoi, giau protein thuc vat va niacin.', 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('chickpeas', 'LEGUMES_NUTS', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '41301990'), 'Đậu gà', 'Đậu gà nấu chín', 'Hạt đậu gà nấu mềm, giàu chất xơ hòa tan và đạm nạc thực vật.', 'PRIORITIZE', 'Protein thực vật tuyệt vời cho sức khỏe tim mạch', 'Chỉ số đường huyết thấp, giàu chất xơ hòa tan giúp hỗ trợ kiểm soát mỡ máu.', NULL, NULL, NULL, 'fiber,protein,potassium,energy', NULL, 'dau ga dau ga nau chin chickpeas, nfs hat dau ga nau mem, giau chat xo hoa tan va dam nac thuc vat.', 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('soybeans', 'LEGUMES_NUTS', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '41107010'), 'Đậu nành', 'Đậu nành luộc chín', 'Nguồn đạm thực vật hoàn chỉnh chứa đầy đủ axit amin thiết yếu.', 'PRIORITIZE', 'Đạm hoàn chỉnh thay thế thịt đỏ', 'Hàm lượng kali và đạm cao, rất phù hợp trong chế độ ăn giảm bớt thịt đỏ nhiều mỡ.', NULL, NULL, NULL, 'protein,potassium,magnesium,fiber', NULL, 'dau nanh dau nanh luoc chin soybeans, cooked nguon dam thuc vat hoan chinh chua day du axit amin thiet yeu.', 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('coffee-brewed', 'BEVERAGES_CAUTION', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '92101000'), 'Cà phê', 'Cà phê phin / pha máy nguyên chất', 'Cà phê đen nguyên chất không thêm đường sữa, chứa caffeine và chất chống oxy hóa tự nhiên.', 'CAUTION', 'Lắng nghe phản ứng nhịp tim của cơ thể', 'Caffeine không cần phải tránh hoàn toàn ở tất cả người có rung nhĩ. Nhiều nghiên cứu cho thấy lượng caffeine vừa phải (1-2 tách mỗi ngày) thường không làm khởi phát cơn nhịp nhanh, tuy nhiên một số người có thể nhạy cảm hơn.', 'Cà phê nguyên chất không thêm đường sữa chứa các chất chống oxy hóa tự nhiên và thường an toàn với hệ tim mạch ở liều lượng hợp lý.', 'Nếu bạn nhận thấy nhịp tim đập nhanh hoặc cảm giác hồi hộp, đánh trống ngực sau khi uống cà phê, hãy giảm lượng dùng hoặc chuyển sang loại đã khử caffeine (decaf).', NULL, 'caffeine,energy,potassium,sodium', NULL, 'ca phe ca phe phin / pha may nguyen chat coffee, brewed ca phe den nguyen chat khong them duong sua, chua caffeine va chat chong oxy hoa tu nhien.', 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('tea-brewed', 'BEVERAGES_CAUTION', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '92303010'), 'Trà xanh', 'Trà xanh pha ấm nóng', 'Trà xanh giàu polyphenol (EGCG) và có hàm lượng caffeine thấp hơn cà phê.', 'CAUTION', 'Hàm lượng caffeine nhẹ, theo dõi sự nhạy cảm cá nhân', 'Lượng caffeine trong trà xanh chỉ bằng khoảng 1/4 so với cà phê, giàu chất chống oxy hóa nhưng người có nhịp tim nhạy cảm vẫn nên uống điều độ.', NULL, NULL, NULL, 'caffeine,potassium,energy', NULL, 'tra xanh tra xanh pha am nong tea, hot, leaf, green tra xanh giau polyphenol (egcg) va co ham luong caffeine thap hon ca phe.', 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('beer-regular', 'BEVERAGES_ALCOHOL', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '93101000'), 'Bia', 'Bia truyền thống', 'Đồ uống có cồn lên men từ ngũ cốc và hoa bia, chứa khoảng 4.5 - 5% cồn.', 'LIMIT', 'Nên hạn chế tối đa', 'Việc uống rượu bia có liên quan đến nguy cơ xuất hiện hoặc tái phát rung nhĩ, đặc biệt ở người uống thường xuyên hoặc uống lượng nhiều.', 'Cồn có thể gây tăng huyết áp, rối loạn chức năng co bóp thất trái và tương tác bất lợi với các thuốc điều trị tim mạch.', 'Hướng dẫn của Hiệp hội Tim mạch Hoa Kỳ (ACC/AHA 2023) khuyến nghị bệnh nhân rung nhĩ nên kiêng hoặc giảm tối đa việc uống thức uống có cồn.', NULL, 'alcohol,energy,carbohydrate,sodium', NULL, 'bia bia truyen thong beer do uong co con len men tu ngu coc va hoa bia, chua khoang 4.5 - 5% con.', 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('wine-red', 'BEVERAGES_ALCOHOL', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '93401010'), 'Rượu vang', 'Rượu vang đỏ', 'Rượu lên men từ nho với nồng độ cồn khoảng 12 - 14%.', 'LIMIT', 'Nên hạn chế ở người có triệu chứng nhịp tim', 'Dù có chứa polyphenol, cồn trong rượu vang vẫn là yếu tố kích thích có thể làm xuất hiện cơn rung nhĩ kịch phát ở người nhạy cảm.', 'Lợi ích tim mạch của chất chống oxy hóa không bù đắp được rủi ro gây rối loạn nhịp và tăng huyết áp do nồng độ cồn mang lại.', NULL, NULL, 'alcohol,energy,carbohydrate,potassium', NULL, 'ruou vang ruou vang do wine, red ruou len men tu nho voi nong do con khoang 12 - 14%.', 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22'),
('beef-sausage', 'PROCESSED_FOODS', (SELECT id FROM nutrition_foods WHERE source = 'USDA_FNDDS' AND source_food_code = '25220105'), 'Xúc xích', 'Xúc xích bò xông khói', 'Thịt chế biến sẵn qua xử lý tẩm ướp và xông khói, có lượng muối natri và chất béo bão hòa rất cao.', 'LIMIT', 'Nên hạn chế trong chế độ ăn hàng ngày', 'Lượng natri rất cao (trên 800mg/100g) cùng chất béo bão hòa cao làm tăng gánh nặng lên huyết áp.', 'Tiêu thụ nhiều thịt chế biến sẵn liên quan trực tiếp đến tăng huyết áp và xơ vữa động mạch.', NULL, NULL, 'sodium,fat_saturated,fat_total,energy', NULL, 'xuc xich xuc xich bo xong khoi beef sausage thit che bien san qua xu ly tam uop va xong khoi, co luong muoi natri va chat beo bao hoa rat cao.', 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'migration:nutrition-guidance-v22', 'migration:nutrition-guidance-v22');

INSERT INTO nutrition_guidance_food_evidence (guidance_food_id, evidence_source_id, display_order) VALUES
('milk-low-fat-1', 'acc-aha-2023', 0),
('milk-low-fat-1', 'cleveland-dietary-af', 1),
('milk-skim', 'acc-aha-2023', 0),
('milk-reduced-fat-2', 'cleveland-dietary-af', 0),
('milk-whole', 'aha-lifestyle-2020', 0),
('milk-lactose-free-low-fat', 'cleveland-dietary-af', 0),
('milk-lactose-free-skim', 'cleveland-dietary-af', 0),
('milk-lactose-free-whole', 'aha-lifestyle-2020', 0),
('salmon-baked', 'acc-aha-2023', 0),
('salmon-baked', 'predimed-trial', 1),
('salmon-fried', 'aha-lifestyle-2020', 0),
('mackerel-grilled', 'acc-aha-2023', 0),
('tuna-canned', 'cleveland-dietary-af', 0),
('spinach-cooked', 'acc-aha-2023', 0),
('spinach-cooked', 'cleveland-dietary-af', 1),
('spinach-raw', 'cleveland-dietary-af', 0),
('broccoli-cooked', 'aha-lifestyle-2020', 0),
('tomato-raw', 'cleveland-dietary-af', 0),
('carrot-raw', 'aha-lifestyle-2020', 0),
('banana-raw', 'acc-aha-2023', 0),
('banana-raw', 'cleveland-dietary-af', 1),
('apple-raw', 'aha-lifestyle-2020', 0),
('orange-raw', 'cleveland-dietary-af', 0),
('avocado-raw', 'predimed-trial', 0),
('avocado-raw', 'aha-lifestyle-2020', 1),
('almonds', 'predimed-trial', 0),
('almonds', 'cleveland-dietary-af', 1),
('peanuts', 'aha-lifestyle-2020', 0),
('chickpeas', 'acc-aha-2023', 0),
('soybeans', 'aha-lifestyle-2020', 0),
('coffee-brewed', 'acc-aha-2023', 0),
('coffee-brewed', 'coffee-af-meta-2021', 1),
('coffee-brewed', 'cleveland-dietary-af', 2),
('tea-brewed', 'coffee-af-meta-2021', 0),
('beer-regular', 'acc-aha-2023', 0),
('beer-regular', 'alcohol-af-review', 1),
('beer-regular', 'aha-lifestyle-2020', 2),
('wine-red', 'acc-aha-2023', 0),
('wine-red', 'alcohol-af-review', 1),
('beef-sausage', 'acc-aha-2023', 0),
('beef-sausage', 'cleveland-dietary-af', 1);
